import React, { useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, ArrowUpRight, Check, Github, Instagram, Mail, Menu, Twitter, X, Zap } from "lucide-react";

const AMAZON = "https://amazon.com/author/janeduru";
const GUMROAD = "https://iamjaneezystore.gumroad.com";
const COFFEE = "https://buymeacoffee.com/janeezyoffb";
const BOOKING = "mailto:zemiolabs@gmail.com?subject=Book%20a%20consulting%20call%20with%20Jane";
const tools = ["React", "React Native", "Expo", "TypeScript", "JavaScript", "Tailwind", "REST APIs", "Testing & QA", "Jira Automation", "AI Workflows"];
const books = [
  { title:"Quiet the Noise", cover:"/quiet-the-noise.png" },
  { title:"Selective Empathy", cover:"/book-selective-empathy.png" },
  { title:"50 AI Prompts to Make Money", cover:"/book-ai-prompts.png" },
];

export default function Portfolio() {
  const [menuOpen,setMenuOpen] = useState(false);
  const [email,setEmail] = useState("");
  const [status,setStatus] = useState("idle");
  const scrollTo = (id) => { setMenuOpen(false); document.getElementById(id)?.scrollIntoView({behavior:"smooth"}); };
  const joinWaitlist = async (event) => {
    event.preventDefault(); setStatus("loading");
    try {
      const response = await fetch("https://formsubmit.co/ajax/zemiolabs@gmail.com", { method:"POST", headers:{"Content-Type":"application/json",Accept:"application/json"}, body:JSON.stringify({email,product:"AfterFight",_subject:"New AfterFight waitlist signup",_captcha:"false"}) });
      if (!response.ok) throw new Error(); setEmail(""); setStatus("success");
    } catch { setStatus("error"); }
  };

  return <main className="site">
    <style>{`
      @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap');
      :root{--ink:#18151d;--muted:#716a77;--paper:#fffdf9;--line:#e9e2dc;--pink:#ff6475;--night:#211b2c}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font-family:'DM Sans',sans-serif}button,input{font:inherit}a{color:inherit;text-decoration:none}
      .site{min-height:100vh;overflow:hidden;background:radial-gradient(circle at 8% 10%,#ffe9e5 0,transparent 25%),radial-gradient(circle at 92% 8%,#eee9ff 0,transparent 25%),var(--paper)}.wrap{width:min(1180px,calc(100% - 40px));margin:auto}
      .nav{height:80px;display:flex;align-items:center;justify-content:space-between}.brand{width:48px;height:48px;display:grid;place-items:center;border:0;border-radius:16px;background:var(--ink);color:#fff;font:800 16px Manrope;cursor:pointer;box-shadow:0 12px 30px #2e24372b}.brand i{font-style:normal;color:#ff99a5}.navlinks{display:flex;align-items:center;gap:28px}.navlinks button{border:0;background:none;color:var(--muted);font-weight:700;cursor:pointer}.navlinks button:hover{color:var(--ink)}.nav-cta,.btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;border-radius:999px;font-weight:800;transition:.25s ease}.nav-cta{padding:11px 18px;background:var(--ink);color:#fff}.menu{display:none;border:0;background:none}.mobile{position:absolute;z-index:20;top:70px;left:20px;right:20px;padding:16px;background:#fff;border:1px solid var(--line);border-radius:20px;box-shadow:0 20px 60px #2c22321f}.mobile button{width:100%;border:0;background:#faf7f4;padding:14px;text-align:left;border-radius:12px;margin:3px 0;font-weight:800}
      .hero{min-height:760px;display:grid;grid-template-columns:1.14fr .86fr;gap:72px;align-items:center;padding:65px 0 90px}.overline{display:inline-flex;align-items:center;gap:8px;padding:8px 12px;border:1px solid #ded5ff;border-radius:999px;background:#f2efff;color:#6954cf;font-size:11px;font-weight:800;letter-spacing:.11em;text-transform:uppercase}.hero h1,.title,.about h2,.bookcopy h2,.aftercopy h2{font-family:Manrope;margin:0;letter-spacing:-.055em}.hero h1{margin-top:24px;font-size:clamp(58px,7.6vw,104px);line-height:.92}.hero h1 span{display:block;color:var(--pink)}.lead{max-width:650px;margin:28px 0 0;color:var(--muted);font-size:19px;line-height:1.65}.role{max-width:690px;margin-top:17px;font-size:12px;font-weight:800;line-height:1.8}.actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:30px}.btn{padding:15px 22px;border:1px solid var(--line);background:#fff}.btn.dark{border-color:var(--ink);background:var(--ink);color:#fff}.btn:hover{transform:translateY(-3px);box-shadow:0 12px 28px #3026371f}
      .heroart{position:relative;height:610px}.portrait{position:absolute;inset:25px 12px 25px 42px;padding:12px;background:#fff;border-radius:42px;box-shadow:0 35px 100px #3d2c511f;animation:drift 5s ease-in-out infinite alternate}.portrait img{width:100%;height:100%;object-fit:cover;object-position:top;border-radius:32px}.orbit{position:absolute;border:1px solid #d7cffa;border-radius:50%;animation:spin 16s linear infinite}.orbit.one{width:180px;height:180px;right:-65px;top:-6px}.orbit.two{width:110px;height:110px;left:-10px;bottom:18px;animation-direction:reverse}.dot{position:absolute;width:18px;height:18px;border-radius:50%;background:var(--pink);top:14px;left:22px;box-shadow:0 0 0 8px #ff64752b}.mini{position:absolute;z-index:3;padding:14px 17px;border-radius:18px;background:#fff;box-shadow:0 18px 50px #251b302b;font-weight:800;animation:bob 3.5s ease-in-out infinite alternate}.mini small{display:block;margin-top:4px;color:var(--muted);font-weight:600}.mini.top{right:-12px;top:92px}.mini.bottom{left:-4px;bottom:72px;animation-delay:1s}@keyframes drift{to{transform:translateY(-10px) rotate(-.8deg)}}@keyframes bob{to{transform:translateY(-9px)}}@keyframes spin{to{transform:rotate(360deg)}}
      .expert-console{position:absolute;inset:28px 0 28px 22px;padding:28px;border:1px solid #ded8e5;border-radius:34px;background:#fff;box-shadow:0 35px 100px #3d2c511f;animation:drift 5s ease-in-out infinite alternate}.console-top{display:flex;justify-content:space-between;align-items:center;padding-bottom:20px;border-bottom:1px solid var(--line)}.online{display:flex;align-items:center;gap:8px;font-size:12px;font-weight:800}.online:before{content:'';width:8px;height:8px;border-radius:50%;background:#34c77b;box-shadow:0 0 0 6px #34c77b1c}.console-top small{color:var(--muted)}.console-title{margin:24px 0 15px;font:800 28px Manrope;letter-spacing:-.04em}.lane{display:grid;grid-template-columns:44px 1fr;gap:13px;align-items:center;padding:15px 0;border-top:1px solid #f0ebf1}.lane i{width:44px;height:44px;display:grid;place-items:center;border-radius:14px;background:#f3efff;color:#6c57d4;font-style:normal;font-weight:800}.lane strong{display:block;font:800 15px Manrope}.lane small{display:block;margin-top:3px;color:var(--muted);line-height:1.4}.console-note{margin-top:18px;padding:15px;border-radius:16px;background:#fff0f2;color:#6d3940;font-size:12px;font-weight:700}
      .marquee{overflow:hidden;border-block:1px solid var(--line);background:#fff}.track{display:flex;width:max-content;gap:34px;padding:17px 0;animation:marquee 28s linear infinite}.track span{display:flex;align-items:center;gap:34px;white-space:nowrap;font-size:12px;font-weight:800}.track span:after{content:'✦';color:var(--pink)}@keyframes marquee{to{transform:translateX(-50%)}}
      .section{padding:110px 0}.sectionhead{display:flex;align-items:end;justify-content:space-between;gap:40px;margin-bottom:42px}.kicker{margin-bottom:12px;color:var(--pink);font-size:11px;font-weight:800;letter-spacing:.13em;text-transform:uppercase}.title{font-size:clamp(42px,5.2vw,68px);line-height:1}.note{max-width:390px;color:var(--muted);line-height:1.65}
      .bento{display:grid;grid-template-columns:1.15fr .85fr .85fr;grid-template-rows:220px 220px;gap:16px}.tile{position:relative;overflow:hidden;padding:26px;border:1px solid var(--line);border-radius:28px;background:#fff;transition:.3s ease}.tile:hover{transform:translateY(-7px);box-shadow:0 25px 60px #30263717}.tile.big{grid-row:span 2;background:var(--night);color:#fff}.tile.wide{grid-column:span 2;background:#efeaff}.tile .number{font:800 58px Manrope;letter-spacing:-.07em}.tile strong{position:absolute;left:26px;bottom:52px;font:800 21px Manrope}.tile p{position:absolute;left:26px;right:24px;bottom:18px;margin:0;color:var(--muted);font-size:13px}.tile.big p{color:#bdb4c5}.tileicon{width:44px;height:44px;display:grid;place-items:center;border-radius:15px;background:#fff0f2;color:var(--pink)}.toolcloud{display:flex;flex-wrap:wrap;gap:10px;margin-top:18px}.toolcloud span{padding:9px 12px;border-radius:999px;background:#201b26;color:#fff;font-size:11px;font-weight:800;transition:.2s}.toolcloud span:hover{background:var(--pink);transform:translateY(-3px)}
      .after{padding:58px;border-radius:40px;background:linear-gradient(135deg,#1d1825,#332341 55%,#6d3555);color:#fff;box-shadow:0 34px 90px #3d28482e}.aftergrid{display:grid;grid-template-columns:1fr .92fr;gap:58px;align-items:center}.productmark{width:64px;height:64px;display:grid;place-items:center;border-radius:21px;background:var(--pink);font:800 20px Manrope;transform:rotate(-6deg)}.aftercopy h2{margin-top:26px;font-size:clamp(42px,5.2vw,70px);line-height:1}.aftercopy p{max-width:560px;color:#cfc7d4;font-size:17px;line-height:1.65}.privacy{display:inline-flex;padding:8px 11px;border-radius:999px;background:#ffffff12;color:#ddd4e1;font-size:12px}
      .garden{position:relative;height:260px;margin-top:28px;overflow:hidden;border:1px solid #ffffff1f;border-radius:28px;background:linear-gradient(#25203a 0 62%,#2b4938 62%)}.garden:after{content:'';position:absolute;left:0;right:0;bottom:0;height:52px;background:linear-gradient(90deg,#233c2e,#42674d,#233c2e)}.moon{position:absolute;width:50px;height:50px;right:28px;top:22px;border-radius:50%;background:#fff2be;box-shadow:0 0 50px #ffe991a6;animation:glow 3s ease-in-out infinite alternate}.flower{position:absolute;z-index:2;bottom:38px;font-size:45px;transform-origin:bottom;animation:grow 3.2s ease-in-out infinite alternate}.flower.a{left:12%}.flower.b{left:43%;font-size:34px;animation-delay:.8s}.flower.c{left:70%;font-size:48px;animation-delay:1.3s}.star{position:absolute;width:5px;height:5px;border-radius:50%;background:#ffe68a;box-shadow:0 0 12px #ffe68a;animation:fly 4s ease-in-out infinite alternate}.s1{left:20%;top:26%}.s2{left:58%;top:19%;animation-delay:1s}.s3{left:76%;top:42%;animation-delay:2s}@keyframes grow{to{transform:rotate(5deg) scale(1.08)}}@keyframes glow{to{box-shadow:0 0 75px #ffe991}}@keyframes fly{to{transform:translate(30px,-18px);opacity:.25}}
      .waitlist{padding:30px;border-radius:28px;background:#fff;color:var(--ink);box-shadow:0 22px 70px #0000002e}.waitlist h3{margin:0;font:800 28px Manrope}.waitlist p{color:var(--muted);line-height:1.55}.inputrow{display:flex;gap:8px}.inputrow input{min-width:0;flex:1;padding:15px;border:1px solid var(--line);border-radius:14px;outline:0}.inputrow input:focus{border-color:var(--pink);box-shadow:0 0 0 3px #ff64751c}.inputrow button{padding:0 18px;border:0;border-radius:14px;background:var(--pink);color:#fff;font-weight:800}.status{min-height:18px;margin:11px 0 0!important;font-size:12px!important}.success{color:#16804d!important}.error{color:#b83f49!important}
      .history{display:grid;grid-template-columns:.9fr 1.1fr;gap:60px;align-items:start}.timeline{display:grid;gap:12px}.time{display:grid;grid-template-columns:80px 1fr;gap:18px;padding:22px;border:1px solid var(--line);border-radius:22px;background:#fff;transition:.25s}.time:hover{transform:translateX(7px);border-color:#d7cbff}.time b{font:800 13px Manrope;color:var(--pink)}.time strong{font:800 18px Manrope}.time p{margin:6px 0 0;color:var(--muted);font-size:13px;line-height:1.55}
      .casegrid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.case{min-height:330px;display:flex;flex-direction:column;padding:28px;border:1px solid var(--line);border-radius:28px;background:#fff;transition:.3s}.case:hover{transform:translateY(-8px);box-shadow:0 28px 70px #30263717}.case:nth-child(2){background:#efeaff}.case:nth-child(3){background:#1d1922;color:#fff}.case-tag{font-size:11px;font-weight:800;letter-spacing:.1em;text-transform:uppercase;color:var(--pink)}.case h3{margin:24px 0 10px;font:800 28px Manrope;letter-spacing:-.04em}.case p{margin:0;color:var(--muted);line-height:1.6}.case:nth-child(3) p{color:#bfb6c4}.metrics{display:flex;gap:22px;margin-top:auto;padding-top:26px}.metrics b{display:block;font:800 23px Manrope}.metrics small{color:var(--muted)}
      .bookhero{display:grid;grid-template-columns:.7fr 1.3fr;gap:62px;align-items:center;padding:48px;border-radius:36px;background:#ede8ff}.bookhero img{width:100%;max-height:480px;object-fit:contain;filter:drop-shadow(0 24px 26px #382a5733);transition:.35s}.bookhero:hover img{transform:rotate(-2deg) scale(1.025)}.bookcopy h2{font-size:clamp(40px,5vw,65px);line-height:1}.bookcopy p{color:var(--muted);font-size:17px}.bookgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:18px}.book{padding:18px;border:1px solid var(--line);border-radius:24px;background:#fff;transition:.3s}.book:hover{transform:translateY(-7px);box-shadow:0 24px 55px #30263717}.book img{width:100%;height:280px;object-fit:contain;background:#f7f3ef;border-radius:16px}.book h3{font:800 18px Manrope}.book a{color:var(--pink);font-size:13px;font-weight:800}
      .about{display:grid;grid-template-columns:1.05fr .95fr;gap:70px;align-items:center}.about h2{font-size:clamp(42px,5vw,66px);line-height:1}.about p{color:var(--muted);font-size:18px;line-height:1.75}.checks{display:grid;gap:10px}.check{display:flex;align-items:center;gap:12px;padding:16px;border:1px solid var(--line);border-radius:17px;background:#fff;font-weight:800}.check svg{color:var(--pink)}
      .support{display:grid;grid-template-columns:1fr auto;gap:30px;align-items:center;margin-bottom:100px;padding:38px 42px;border-radius:32px;background:var(--ink);color:#fff;box-shadow:0 28px 80px #2f25371f}.support h2{margin:0;font:800 clamp(30px,4vw,48px) Manrope;letter-spacing:-.04em}.support p{margin:8px 0 0;color:#bfb7c5}.support .btn{border-color:#fff;background:#fff;color:var(--ink)}footer{padding:42px 0;border-top:1px solid var(--line)}.footer{display:flex;align-items:center;justify-content:space-between;gap:20px}.socials{display:flex;gap:9px}.socials a{width:40px;height:40px;display:grid;place-items:center;border:1px solid var(--line);border-radius:50%;background:#fff}
      .consult{margin-bottom:18px;background:linear-gradient(135deg,#efeaff,#ffe8e8);color:var(--ink)}.consult p{color:var(--muted)}.consult .btn{border-color:var(--ink);background:var(--ink);color:#fff}
      @media(max-width:900px){.navlinks{display:none}.menu{display:block}.hero,.aftergrid,.history,.bookhero,.about,.support{grid-template-columns:1fr}.hero{padding-top:35px}.heroart{height:560px}.bento{grid-template-columns:1fr 1fr;grid-template-rows:auto}.tile,.tile.big,.tile.wide{grid-column:auto;grid-row:auto;min-height:230px}.sectionhead{display:block}.note{margin-top:15px}.bookgrid{grid-template-columns:1fr 1fr}.casegrid{grid-template-columns:1fr}}
      @media(max-width:600px){.wrap{width:min(100% - 28px,1180px)}.hero{min-height:auto;gap:38px;padding-bottom:65px}.hero h1{font-size:54px}.lead{font-size:17px}.heroart{height:455px}.portrait{inset:12px 4px 18px 22px}.mini{font-size:12px}.mini.top{right:0}.mini.bottom{left:0}.section{padding:76px 0}.bento,.bookgrid{grid-template-columns:1fr}.after{padding:30px 20px;border-radius:28px}.garden{height:210px}.inputrow{display:grid}.inputrow button{padding:14px}.history{gap:28px}.time{grid-template-columns:58px 1fr}.bookhero{padding:28px 20px}.book img{height:330px}.support{padding:28px 24px}.footer{align-items:flex-start;flex-direction:column}}
      @media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.01ms!important;animation-iteration-count:1!important;scroll-behavior:auto!important}}
    `}</style>
    <header className="wrap"><nav className="nav"><button className="brand" onClick={()=>scrollTo("top")} aria-label="Jane Duru home">J<i>D</i></button><div className="navlinks"><button onClick={()=>scrollTo("work")}>Expertise</button><button onClick={()=>scrollTo("proof")}>Proof</button><button onClick={()=>scrollTo("build")}>Building</button><button onClick={()=>scrollTo("books")}>Books</button><a className="nav-cta" href={BOOKING}>Book Jane</a></div><button className="menu" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Open menu">{menuOpen?<X/>:<Menu/>}</button>{menuOpen&&<div className="mobile"><button onClick={()=>scrollTo("work")}>Expertise</button><button onClick={()=>scrollTo("proof")}>Proof</button><button onClick={()=>scrollTo("build")}>Building</button><button onClick={()=>scrollTo("books")}>Books</button></div>}</nav></header>
    <section className="wrap hero" id="top"><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.7}}><span className="overline"><Zap size={13}/> Software · Automation · Customer systems</span><h1>I build products.<span>I improve operations.</span></h1><p className="lead">I combine technical support, customer enablement, fintech experience and frontend engineering to build better software—and automate the work behind it.</p><p className="role">FINTECH & PAYMENTS · SAAS · FRONTEND & MOBILE · SUPPORT AUTOMATION · PRODUCT</p><div className="actions"><a className="btn dark" href={BOOKING}>Book a consulting call <ArrowRight size={17}/></a><button className="btn" onClick={()=>scrollTo("proof")}>See proof of work</button></div></motion.div><div className="heroart"><div className="orbit one"><i className="dot"/></div><div className="orbit two"><i className="dot"/></div><div className="expert-console"><div className="console-top"><span className="online">Available for select projects</span><small>Jane Duru</small></div><h3 className="console-title">Where I create value</h3><div className="lane"><i>01</i><div><strong>Support & enablement</strong><small>Systems that help customers and teams succeed.</small></div></div><div className="lane"><i>02</i><div><strong>Automation</strong><small>Less manual work. Faster, clearer operations.</small></div></div><div className="lane"><i>03</i><div><strong>Frontend engineering</strong><small>Useful web and mobile product experiences.</small></div></div><div className="lane"><i>04</i><div><strong>Product building</strong><small>From a real problem to a shipped solution.</small></div></div><div className="console-note">8+ years across customers, financial services and technology.</div></div></div></section>
    <div className="marquee"><div className="track">{[...tools,...tools].map((tool,i)=><span key={`${tool}-${i}`}>{tool}</span>)}</div></div>
    <section className="wrap section" id="work"><div className="sectionhead"><div><div className="kicker">Core expertise</div><h2 className="title">Customer insight.<br/>Technical execution.</h2></div><p className="note">I work where customer experience, operations and product engineering meet.</p></div><div className="bento"><article className="tile big"><div className="number">8+</div><strong>Commercial & customer expertise</strong><p>Sales · Customer service · Financial services · Fintech</p></article><article className="tile"><div className="tileicon">01</div><strong>Support & enablement</strong><p>Troubleshooting · Knowledge systems · QA · Customer journeys</p></article><article className="tile"><div className="tileicon">02</div><strong>Frontend & mobile</strong><p>React · React Native · Expo · TypeScript</p></article><article className="tile wide"><div className="tileicon">03</div><strong>Automation & product</strong><p>Jira automation · AI workflows · REST APIs · Product execution</p></article></div><div className="toolcloud">{tools.map(tool=><span key={tool}>{tool}</span>)}</div></section>
    <section className="wrap section" id="build"><div className="after"><div className="aftergrid"><div className="aftercopy"><div className="productmark">AF</div><h2>Love after the hard moment.</h2><p>AfterFight is a private, thoughtful experience for couples who want a better way forward after difficult moments.</p><span className="privacy">The outcome is public. The mechanics stay private.</span><div className="garden" aria-label="Animated night garden symbolizing growth"><i className="moon"/><span className="flower a">🌷</span><span className="flower b">🌼</span><span className="flower c">🌸</span><i className="star s1"/><i className="star s2"/><i className="star s3"/></div></div><form className="waitlist" id="waitlist" onSubmit={joinWaitlist}><div className="kicker">Private beta</div><h3>Be first to try it.</h3><p>Join for thoughtful updates and early access.</p><div className="inputrow"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Your email address" required/><button disabled={status==="loading"}>{status==="loading"?"Joining…":"Join"}</button></div><p className={`status ${status}`}>{status==="success"&&"You’re on the list."}{status==="error"&&"Please try again."}{status==="idle"&&"No noise. Only meaningful updates."}</p></form></div></div></section>
    <section className="wrap section" id="proof"><div className="sectionhead"><div><div className="kicker">Selected proof</div><h2 className="title">I don’t only advise.<br/>I build.</h2></div><p className="note">A mix of shipped products, operational systems and current founder work.</p></div><div className="casegrid"><article className="case"><span className="case-tag">Shipped product</span><h3>Ohh</h3><p>A relationship app launched on iOS and Android, grown from product idea to paying users, then intentionally closed after the lessons were clear.</p><div className="metrics"><div><b>4,250+</b><small>Cards</small></div><div><b>85</b><small>Decks</small></div><div><b>2</b><small>Platforms</small></div></div></article><article className="case"><span className="case-tag">Operations</span><h3>Support automation</h3><p>Designing Jira automations, clearer workflows and enablement systems that reduce repetitive support work and help teams respond consistently.</p><div className="metrics"><div><b>Jira</b><small>Automation</small></div><div><b>QA</b><small>Testing</small></div></div></article><article className="case"><span className="case-tag">Founder work</span><h3>AfterFight</h3><p>A new relationship product being built from a real human problem. The promise is public; the product mechanics stay private.</p><div className="metrics"><div><b>Now</b><small>Building</small></div><div><b>Next</b><small>Private beta</small></div></div></article></div></section>
    <section className="wrap section" id="books"><div className="bookhero"><img src="/new-book.jpg" alt="Nobody Pays You for Working Hard Anymore book cover"/><div className="bookcopy"><div className="kicker">Newest book</div><h2>Nobody Pays You for Working Hard Anymore</h2><p>Create value. Build leverage. Make money in the age of AI.</p><div className="actions"><a className="btn dark" href={AMAZON} target="_blank" rel="noreferrer">Amazon <ArrowUpRight size={16}/></a><a className="btn" href={GUMROAD} target="_blank" rel="noreferrer">Gumroad <ArrowUpRight size={16}/></a></div></div></div><div className="bookgrid">{books.map(book=><article className="book" key={book.title}><img src={book.cover} alt={`${book.title} book cover`}/><h3>{book.title}</h3><a href={AMAZON} target="_blank" rel="noreferrer">View book ↗</a></article>)}</div></section>
    <section className="wrap section about" id="about"><div><div className="kicker">About Jane</div><h2>Builder’s mind.<br/>Operator’s instinct.</h2><p>I’m Jane Duru, co-founder of Zemio Labs. I build and consult on apps, software and automation for people and businesses—while creating products of my own.</p><div className="actions"><a className="btn dark" href="https://zemiolabs.com" target="_blank" rel="noreferrer">Zemio Labs <ArrowUpRight size={16}/></a><a className="btn" href="https://github.com/janeezy" target="_blank" rel="noreferrer">GitHub <Github size={16}/></a></div></div><div className="checks">{["Frontend & mobile engineering","Technical support & enablement","Fintech, payments & SaaS","Automation & AI workflows","Product strategy & execution","Author and founder"].map(item=><div className="check" key={item}><Check size={18}/>{item}</div>)}</div></section>
    <section className="wrap support consult"><div><h2>Need better customer systems or a product built?</h2><p>Book Jane for product, frontend, automation or support-operations consulting.</p></div><a className="btn" href={BOOKING}>Book a call <ArrowRight size={17}/></a></section>
    <section className="wrap support"><div><h2>Support what I’m building next.</h2><p>Back an independent builder, writer and product experimenter.</p></div><a className="btn" href={COFFEE} target="_blank" rel="noreferrer">☕ Support my build</a></section>
    <footer><div className="wrap footer"><div><div className="brand">J<i>D</i></div><small>Building useful things from real problems.</small></div><div className="socials"><a href="https://x.com/Iamjaneezy" target="_blank" rel="noreferrer" aria-label="X"><Twitter size={17}/></a><a href="https://github.com/janeezy" target="_blank" rel="noreferrer" aria-label="GitHub"><Github size={17}/></a><a href="https://www.instagram.com/iamjaneezy" target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={17}/></a><a href="mailto:zemiolabs@gmail.com" aria-label="Email"><Mail size={17}/></a></div></div></footer>
  </main>;
}
